superproject/blog/urls.py
from django.urls import path
from blog.views import AllPostsView, SinglePostsView, CreatePostView, UpdatePostView, DeletePostView

app_name = "blog"

urlpatterns = [

    path ("", AllPostsView.as_view(), name="all"),
    path("<int:pk>/", SinglePostsView.as_view(), name="single"),
    path("new/", CreatePostView.as_view(), name="new"),
    path("<int:pk>/update/", UpdatePostView.as_view(), name="update"),
    path("<int:pk>/delete/", DeletePostView.as_view(), name="delete"),

]

superproject/project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponse, HttpRequest
from django.urls import path, include

from project.views import SignUpView
from task4.views import info


def hello_world(request: HttpRequest):
    x = str(request.headers)
    return HttpResponse(x)


urlpatterns = [
        path('admin/', admin.site.urls),
        path('hw/', hello_world),
        path('task4/', include("task4.urls")),
        path("blog/", include ("blog.urls")),
        path("signup/", SignUpView.as_view(), name='signup'),
        path("login/", LoginView.as_view(), name='login'),
        path("logout/", LogoutView.as_view(), name='logout')
]

superproject/task4/urls.py
from django.urls import path

from task4.views import view,  InfoView
from task4.views import ShowNumbersView


urlpatterns = [
    path('task/', view),
    path("shogun/", ShowNumbersView.as_view()),
    path ('info/' , InfoView.as_view()),
]

superproject/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse_lazy

User = get_user_model()
class Post(models.Model):
    title = models.TextField()
    content = models.TextField(blank=True, null=True)
    hidden = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self) -> str:
        return reverse_lazy("blog:single", kwargs={"pk": self.pk})

        def __repr__(self):
            lock_sign = "🔒" if self.hidden else ""
            class_name = self.__class__.__name__
            kwargs = {
                "pk": self.pk,
                "title": self.title,
            }
            kwargs_text_parts = (f"{arg}={value!r}" for arg, value in kwargs.items())
            kwargs_text = ", ".join(kwargs_text_parts)

            return f"{lock_sign}{class_name}({kwargs_text})"

        __str__ = __repr__

superproject/task4/models.py
from django.db import models

class NumbersManager(models.Model):
    pass
class Numbers(models.Model):
    objects = NumbersManager()
    name = models.TextField(unique=True)
    n = models.BigIntegerField(default=0)

    def __repr__(self):
        return f"{self.__class__.__name__}(id = {self.id}, name = {self.name}, n = {self.n}) "

superproject/blog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Post


PAGE_SIZE = 50


class OwnerMixin:
    def get_queryset(self):
        k = super().get_queryset().filter(author=self.request.user)
        return k

class BlogMixin:
    fields = ["title", "content", "hidden"]
    model = Post
    success_url = reverse_lazy("blog:all")



class AllPostsView(BlogMixin, ListView):
    def get_queryset(self):
        return super().get_queryset().filter(hidden=False).order_by("pk")[:PAGE_SIZE]


class SinglePostsView(LoginRequiredMixin,BlogMixin,DetailView):
    pass

class CreatePostView(LoginRequiredMixin,BlogMixin, CreateView):
    fields = ["title", "content", "hidden"]

    def form_valid(self, form):

        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return super().form_valid(form)

class UpdatePostView(LoginRequiredMixin,BlogMixin,OwnerMixin,UpdateView):
    pass

class DeletePostView(LoginRequiredMixin,BlogMixin,OwnerMixin,DeleteView):
    pass

superproject/project/views.py
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

User = get_user_model()


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = "registration/login.html"
    extra_context = {"action": "SIGN UP"}
    success_url = reverse_lazy("blog:all")
    
    def form_valid(self, form):
        form = form.save()
        user = authenticate(
            username=form.cleaned_data.get("username"),
            password=form.clean_password2(),
        )
        login(self.request, user)
        return super().form_valid(form)

superproject/task4/views.py
from django.http import HttpRequest, HttpResponse
import json
from typing import Optional, Tuple
from task4.models import Numbers
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.views.generic import ListView, TemplateView


def view(request: HttpRequest, obj=None) -> HttpResponse:
    name = ''
    try:
        obj.Numbers.objects.get(name=name)
        n = obj.n
    except:
        n = -1
    return HttpResponse(str(n))


def get_user_name(request: HttpRequest) -> Optional[str]:
    username = request.headers.get("x-user") or None
    return username


@csrf_exempt
def task4(request: HttpRequest):
    if request.method != 'POST':
        return HttpResponse(status=405)

    username = get_user_name(request)
    if not username:
        return HttpResponse(status=403)
    name = "MyNumbers"
    obj: Tuple[Numbers, bool] = Numbers.objects.get_or_create(name=name)
    cell, _created = obj

    body = json.loads(request.body)
    if not body:
        return HttpResponse(status=422)
    else:
        if type(body) == str:
            if body == "stop" or body == '"stop"' or body == "'stop'":
                counter = cell.n
                cell.n = 0
                cell.save()
                return HttpResponse(counter)
            if body.isdigit() or body == "0":
                return HttpResponse(status=422)
        elif type(body) == int:
            if body <= -101 or body >= 101:
                return HttpResponse(status=422)

            else:
                cell.n += body
                cell.save()
                return HttpResponse(cell.n)


def info(request: HttpRequest) -> HttpResponse:

    numbers = Numbers.objects.all()
    return render(request, "task4/info.html", {"n": numbers})


class ShowNumbersView(ListView):
    template_name = "task4/info.html"
    model = Numbers

class InfoView(TemplateView):
    template_name = "task4/info.html"
    extra_context = {"n": Numbers.objects.all()}

superproject/blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if object.author == user %}
        <p>Удаляем {{ object }}</p>
        <p>Ты уверен?</p>
        <form method="POST">
            {% csrf_token %}
            <button type="submit">Да</button>
        </form>
        <p><a href="{% url 'blog:all' %}">(назад ко всем постам)</a></p>
    {% endif %}
</body>
</html>

superproject/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<article>
    <h1>{{ object.title }}</h1>
    <p>
    <form  action = "{% url 'blog:all' %}">
    <button> BACK TO ALL POSTS </button>
    </form>
    </p>
    {% if object.author == user %}
        <p>
            <form  action = "{% url 'blog:update' object.pk %}">
            <button> UPDATE POST </button>
            </form>
        </p>
        <p>
            <form  action ="{% url 'blog:delete' object.pk %}">
            <button> DELETE POST </button>
            </form>
        <p>
    {% endif %}
    <hr>
    <p>{{ post.content|default:"NO CONTENT" }}</p>
</article>
</body>
</html>

superproject/blog/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Отправить </button>
</form>

</body>
</html>

superproject/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p> Me: {{ user }}</p>
    {% if user.is_authenticated %}
        <form  action = "{% url 'logout' %}">
                <button> LOG OUT </button>
        </form>
    {% else %}
    <p><form  action = "{% url 'login' %}">
                <button> LOG IN </button>
    </form></p>
    <p><form  action = "{% url 'signup' %}">
                <button> SIGN UP </button>
    </form></p>
    {% endif %}
<article>
    <h1>All posts</h1>
    {% if not user.is_anonymous %}
        <a href= "{% url 'blog:new' %}"> NEW POST  </a>
    {% else %}
       <form  action = "{% url 'login' %}">
                <button> LOG IN </button>
    {% endif %}
    <hr>
    {% for post in object_list %}
        <section id="id_post_{{ post.pk }}">
            <a href="{{ post.get_absolute_url }}"><h2>{{ post.title }}</h2></a>
            <p>{{ post.content|default:"NO CONTENT" }}</p>
            <p>Author: {{ post.author }}</p>
        </section>
        {% empty %}
            <p>(no posts)</p>
        {% if not user.is_anonymous %}
        <p>
            <form action="/blog/new/">
            <button> CREATE </button>
            </form>
        </p>
        {% endif %}
    {% endfor %}
</article>
</body>
</html>

superproject/task4/templates/task4/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HAT></title>
</head>
<body>
{{n}}
<div> {{ object_list }}</div>
</body>
</html>